### ISSUE TITLE
Setup file

### ISSUE THREAD

**Issue by paboma** [nyx0/Tinba#1]
Hello please where is the builder for Tinba

**Comment by nyx0** [comment]
@paboma It comes without builder iirc

**Comment by paboma** [comment]
Oh, then how do i but.
i have connected it already to the database and i must say it's source code
is amazing, i doubt it was written by one person.

**Comment by paboma** [comment]
Please let me know how i build the file, i was able to connect it to the database

**Comment by nyx0** [comment]
I put this code on GitHub to analyze it, like I said it's not my code therefore I don't know how to build it. If you want to build it, I guess you can take a closer look at the code and create your own builder but I can't help you with that :)
